---
# Deploy docker image on testing environment
- hosts: servers
  become_method: sudo
  remote_user: ansible
  become: true

  vars:

    BUILD_ID: "{{ BUILD_ID }}"
    default_container_image: frenley/development_env:tomcatwebapp-{{ BUILD_ID }}

  tasks:

    - name: Docker images name
      debug:
        msg:
        -  " Container name is : {{ default_container_image }}"

