---
# Deploy docker image on testing environment
- hosts: servers
  become_method: sudo
  remote_user: ansible
  become: true
  
  vars:
       default_container_image: frenley/development_env:tomcatwebapp-50

  tasks:
       
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python-pip']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: 
        - docker
        - requests>=2.20.1

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
     
    - name: build the Docker image
      command: "docker build -t built-by-ansible ."

        
    - name: run the site in a docker container
      docker:
        name: test-container
        image: "built-by-ansible"
        state: reloaded
        publish_all_ports: yes
        use_tls: encrypt
  
